### ISSUE TITLE
Release a version for service provider 0.4.0

### ISSUE THREAD

**Issue by Ngob** [thecodingmachine/middleware-list-universal-module#3]
Hello,

I need you to tag a version to be able to update [PayloadMiddleware](https://github.com/phps-cans/psr7-middlewares-payload-universal-module) to service provider 0.4.0

**Comment by moufmouf** [comment]
Done!

**Comment by moufmouf** [comment]
@Ngob When migrating, you should migrate to thecodingmachine/funky (instead of directly depending on service-providers v0.4). That way, when v0.5 is out, you will have nothing to do.
